### PR TITLE
feat(base/rpchat): better workflow and discord logs

### PR DESCRIPTION
**Pull request by Konijntje-x**
## Proposed Changes

    - discord logs
    - made a better workflow and organized the module

### CODE REVIEW

**Comment by Konijntje-x** [comment]
You must have the discordlog method from pr #21

**Comment by ESXCrackhead** [comment]
If your plan is to add discord logs to multiple modules, then you need to create a module for sending Discord logs.

**Comment by Konijntje-x** [comment]
It was in #21

**Comment by Konijntje-x** [comment]
@ESXCrackhead fixed

**Comment by ESXCrackhead** [comment]
`onClient('logs:toDiscord', function(message, webhook)`

not `esx:logs:toDiscord`

**Comment by ESXCrackhead** [comment]
Additionally, that event is intended for client->server emitServer() and onClient() events, you will have to create a new event for server-server logging

**Comment by ESXCrackhead** [comment]
https://github.com/esx-framework/esx-reborn/commit/b8ec34395b9ac05b96fdaea3a2ae8adb76829b17

**Comment by ESXCrackhead** [comment]
https://github.com/esx-framework/esx-reborn/commit/b8ec34395b9ac05b96fdaea3a2ae8adb76829b17

**Comment by Konijntje-x** [comment]
i'll do it

**Comment by Konijntje-x** [comment]
fixed

**Comment by ArkSeyonet** [comment]
image
This PR contains broken code. You need to test and fix these before the PRs can be merged.

**Comment by ArkSeyonet** [comment]
```
function sendLogs (message,webhook)
  if message == nil or message == '' then return FALSE end
  PerformHttpRequest(webhook, function(err, text, headers) end, 'POST', json.encode({ content = message }), { ['Content-Type'] = 'application/json' })
end

onServer("toDiscord", function(message, webhook)
  sendLogs(message , webhook)
end)
```

onServer **does not** exist in server code, it's onClient

**Pull request merged**
